### PR TITLE
Simplify hex2utf16le

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by tinybike** [comment]
Good catch!  I did not realize Buffers allowed `.toString("utf16le")`, haha.

**Comment by tinybike** [comment]
It appears that `buffer.toString("utf16le")` does not validate the input length.  If there is a trailing single byte, it is silently left out.  For example:
```javascript
> new Buffer("032603", "hex").toString("utf16le")
'☃'
```
So, I will add an explicit length check before converting to string.  Otherwise this looks good.  Thank you!

**Comment by fanatid** [comment]
```js
function hex2utf16le(input) {
  if (input.length % 4 !== 0) {
    throw new Error("Can't convert input to utf16 - invalid length");
  }
  return new Buffer(input, "hex").toString("utf16le");
}
```
will better ;)

**Comment by tinybike** [comment]
Hehe, I suppose that is a bit cleaner.

**Pull request merged**
