### PR TITLE
Remove sjcl package

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by tinybike** [comment]
Hm, did you figure out what was causing the (sometimes) `crypto.pbkdf2==undefined` error?

**Comment by fanatid** [comment]
> Hm, did you figure out what was causing the (sometimes) crypto.pbkdf2==undefined error?

No, I propose release beta version with new packages and find use case when this error, then fix it

**Comment by tinybike** [comment]
Oh ok, sounds good! :thumbsup:

**Comment by fanatid** [comment]
Unfortunately you already release new version 5, but we can release 6-beta for example

**Comment by tinybike** [comment]
Yeah, I made a breaking change to `encrypt` and `decrypt` (they now return Buffers instead of strings), so I wanted to make a new minor version for that.  Am happy to step up to version 0.6 for this though! :smiley:

**Comment by tinybike** [comment]
Closing this for now.  @fanatid please feel free to re-open if needed!

**Pull request closed without merging**
